// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *PutArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Body (datamodel.BlobModel) (struct)
	if len("body") > 8192 {
		return fmt.Errorf("string in field \"body\" was too long")
	}
	if err := jw.WriteString(string("body")); err != nil {
		return fmt.Errorf("writing string for field \"body\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Body.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Body: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Destination (promise.AwaitOK) (struct)
	if len("destination") > 8192 {
		return fmt.Errorf("string in field \"destination\" was too long")
	}
	if err := jw.WriteString(string("destination")); err != nil {
		return fmt.Errorf("writing string for field \"destination\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Destination.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Destination: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *PutArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = PutArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for PutArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for PutArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for PutArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field PutArgumentsModel: string too large")
				}
				return fmt.Errorf("reading string for field PutArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field PutArgumentsModel: %w", err)
			}
			switch name {

			// t.Body (datamodel.BlobModel) (struct)
			case "body":

				if err := t.Body.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Body: %w", err)
				}

				// t.Destination (promise.AwaitOK) (struct)
			case "destination":

				if err := t.Destination.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Destination: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for PutArgumentsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field PutArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for PutArgumentsModel")
			}
		}
	}

	return nil
}
