// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package datamodel

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *ListArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 2

	if t.Cursor == nil {
		fieldCount--
	}

	if t.Size == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Size (uint64) (uint64)
	if t.Size != nil {

		if len("size") > 8192 {
			return xerrors.Errorf("Value in field \"size\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("size"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("size")); err != nil {
			return err
		}

		if t.Size == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(*t.Size)); err != nil {
				return err
			}
		}

	}

	// t.Cursor (string) (string)
	if t.Cursor != nil {

		if len("cursor") > 8192 {
			return xerrors.Errorf("Value in field \"cursor\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("cursor"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("cursor")); err != nil {
			return err
		}

		if t.Cursor == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Cursor) > 8192 {
				return xerrors.Errorf("Value in field t.Cursor was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Cursor))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Cursor)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (t *ListArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ListArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ListArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 6)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Size (uint64) (uint64)
		case "size":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					maj, extra, err = cr.ReadHeader()
					if err != nil {
						return err
					}
					if maj != cbg.MajUnsignedInt {
						return fmt.Errorf("wrong type for uint64 field")
					}
					typed := uint64(extra)
					t.Size = &typed
				}

			}
			// t.Cursor (string) (string)
		case "cursor":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					t.Cursor = (*string)(&sval)
				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *ListOKModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 5

	if t.Cursor == nil {
		fieldCount--
	}

	if t.Before == nil {
		fieldCount--
	}

	if t.After == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return xerrors.Errorf("Value in field \"size\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("size"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("size")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Size)); err != nil {
		return err
	}

	// t.After (string) (string)
	if t.After != nil {

		if len("after") > 8192 {
			return xerrors.Errorf("Value in field \"after\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("after"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("after")); err != nil {
			return err
		}

		if t.After == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.After) > 8192 {
				return xerrors.Errorf("Value in field t.After was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.After))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.After)); err != nil {
				return err
			}
		}
	}

	// t.Before (string) (string)
	if t.Before != nil {

		if len("before") > 8192 {
			return xerrors.Errorf("Value in field \"before\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("before"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("before")); err != nil {
			return err
		}

		if t.Before == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Before) > 8192 {
				return xerrors.Errorf("Value in field t.Before was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Before))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Before)); err != nil {
				return err
			}
		}
	}

	// t.Cursor (string) (string)
	if t.Cursor != nil {

		if len("cursor") > 8192 {
			return xerrors.Errorf("Value in field \"cursor\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("cursor"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("cursor")); err != nil {
			return err
		}

		if t.Cursor == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Cursor) > 8192 {
				return xerrors.Errorf("Value in field t.Cursor was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Cursor))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Cursor)); err != nil {
				return err
			}
		}
	}

	// t.Results ([]datamodel.ListBlobItem) (slice)
	if len("results") > 8192 {
		return xerrors.Errorf("Value in field \"results\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("results"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("results")); err != nil {
		return err
	}

	if len(t.Results) > 8192 {
		return xerrors.Errorf("Slice value in field t.Results was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Results))); err != nil {
		return err
	}
	for _, v := range t.Results {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}
	return nil
}

func (t *ListOKModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ListOKModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ListOKModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 7)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Size (uint64) (uint64)
		case "size":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.Size = uint64(extra)

			}
			// t.After (string) (string)
		case "after":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					t.After = (*string)(&sval)
				}
			}
			// t.Before (string) (string)
		case "before":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					t.Before = (*string)(&sval)
				}
			}
			// t.Cursor (string) (string)
		case "cursor":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					t.Cursor = (*string)(&sval)
				}
			}
			// t.Results ([]datamodel.ListBlobItem) (slice)
		case "results":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Results: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Results = make([]ListBlobItem, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						if err := t.Results[i].UnmarshalCBOR(cr); err != nil {
							return xerrors.Errorf("unmarshaling t.Results[i]: %w", err)
						}

					}

				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *ListBlobItem) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Blob (datamodel.BlobModel) (struct)
	if len("blob") > 8192 {
		return xerrors.Errorf("Value in field \"blob\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("blob"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("blob")); err != nil {
		return err
	}

	if err := t.Blob.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.InsertedAt (uint64) (uint64)
	if len("insertedAt") > 8192 {
		return xerrors.Errorf("Value in field \"insertedAt\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("insertedAt"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("insertedAt")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.InsertedAt)); err != nil {
		return err
	}

	return nil
}

func (t *ListBlobItem) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ListBlobItem{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ListBlobItem: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 10)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Blob (datamodel.BlobModel) (struct)
		case "blob":

			{

				if err := t.Blob.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Blob: %w", err)
				}

			}
			// t.InsertedAt (uint64) (uint64)
		case "insertedAt":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.InsertedAt = uint64(extra)

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
