//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package pdp

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *AcceptArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Blob (multihash.Multihash) (slice)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Blob) > 2097152 {
		return fmt.Errorf("byte array in field t.Blob was too long")
	}

	if err := jw.WriteBytes(t.Blob); err != nil {
		return fmt.Errorf("writing bytes for field t.Blob: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AcceptArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AcceptArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AcceptArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AcceptArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AcceptArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AcceptArguments: string too large")
				}
				return fmt.Errorf("reading string for field AcceptArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AcceptArguments: %w", err)
			}
			switch name {

			// t.Blob (multihash.Multihash) (slice)
			case "blob":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Blob: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Blob: %w", err)
					}
					if len(bval) > 0 {
						t.Blob = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AcceptArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AcceptArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AcceptArguments")
			}
		}
	}

	return nil
}
func (t *AcceptOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Aggregate (cid.Cid) (struct)
	if len("aggregate") > 8192 {
		return fmt.Errorf("string in field \"aggregate\" was too long")
	}
	if err := jw.WriteString(string("aggregate")); err != nil {
		return fmt.Errorf("writing string for field \"aggregate\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Aggregate); err != nil {
		return fmt.Errorf("writing CID for field t.Aggregate: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.InclusionProof (merkletree.ProofData) (struct)
	if len("inclusionProof") > 8192 {
		return fmt.Errorf("string in field \"inclusionProof\" was too long")
	}
	if err := jw.WriteString(string("inclusionProof")); err != nil {
		return fmt.Errorf("writing string for field \"inclusionProof\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.InclusionProof.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.InclusionProof: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Piece (cid.Cid) (struct)
	if len("piece") > 8192 {
		return fmt.Errorf("string in field \"piece\" was too long")
	}
	if err := jw.WriteString(string("piece")); err != nil {
		return fmt.Errorf("writing string for field \"piece\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Piece); err != nil {
		return fmt.Errorf("writing CID for field t.Piece: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AcceptOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AcceptOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AcceptOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AcceptOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AcceptOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AcceptOK: string too large")
				}
				return fmt.Errorf("reading string for field AcceptOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AcceptOK: %w", err)
			}
			switch name {

			// t.Aggregate (cid.Cid) (struct)
			case "aggregate":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Aggregate: %w", err)
					}
					t.Aggregate = c

				}

				// t.InclusionProof (merkletree.ProofData) (struct)
			case "inclusionProof":

				if err := t.InclusionProof.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.InclusionProof: %w", err)
				}

				// t.Piece (cid.Cid) (struct)
			case "piece":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Piece: %w", err)
					}
					t.Piece = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AcceptOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AcceptOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AcceptOK")
			}
		}
	}

	return nil
}
func (t *InfoArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Blob (multihash.Multihash) (slice)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Blob) > 2097152 {
		return fmt.Errorf("byte array in field t.Blob was too long")
	}

	if err := jw.WriteBytes(t.Blob); err != nil {
		return fmt.Errorf("writing bytes for field t.Blob: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *InfoArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = InfoArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for InfoArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for InfoArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for InfoArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field InfoArguments: string too large")
				}
				return fmt.Errorf("reading string for field InfoArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field InfoArguments: %w", err)
			}
			switch name {

			// t.Blob (multihash.Multihash) (slice)
			case "blob":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Blob: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Blob: %w", err)
					}
					if len(bval) > 0 {
						t.Blob = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for InfoArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field InfoArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for InfoArguments")
			}
		}
	}

	return nil
}
func (t *InfoAcceptedAggregate) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Aggregate (cid.Cid) (struct)
	if len("aggregate") > 8192 {
		return fmt.Errorf("string in field \"aggregate\" was too long")
	}
	if err := jw.WriteString(string("aggregate")); err != nil {
		return fmt.Errorf("writing string for field \"aggregate\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Aggregate); err != nil {
		return fmt.Errorf("writing CID for field t.Aggregate: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.InclusionProof (merkletree.ProofData) (struct)
	if len("inclusionProof") > 8192 {
		return fmt.Errorf("string in field \"inclusionProof\" was too long")
	}
	if err := jw.WriteString(string("inclusionProof")); err != nil {
		return fmt.Errorf("writing string for field \"inclusionProof\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.InclusionProof.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.InclusionProof: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *InfoAcceptedAggregate) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = InfoAcceptedAggregate{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for InfoAcceptedAggregate: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for InfoAcceptedAggregate: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for InfoAcceptedAggregate: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field InfoAcceptedAggregate: string too large")
				}
				return fmt.Errorf("reading string for field InfoAcceptedAggregate: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field InfoAcceptedAggregate: %w", err)
			}
			switch name {

			// t.Aggregate (cid.Cid) (struct)
			case "aggregate":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Aggregate: %w", err)
					}
					t.Aggregate = c

				}

				// t.InclusionProof (merkletree.ProofData) (struct)
			case "inclusionProof":

				if err := t.InclusionProof.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.InclusionProof: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for InfoAcceptedAggregate: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field InfoAcceptedAggregate: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for InfoAcceptedAggregate")
			}
		}
	}

	return nil
}
func (t *InfoOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Aggregates ([]pdp.InfoAcceptedAggregate) (slice)
	if len("aggregates") > 8192 {
		return fmt.Errorf("string in field \"aggregates\" was too long")
	}
	if err := jw.WriteString(string("aggregates")); err != nil {
		return fmt.Errorf("writing string for field \"aggregates\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Aggregates) > 8192 {
		return fmt.Errorf("slice value in field t.Aggregates was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Aggregates: %w", err)
	}
	for i, v := range t.Aggregates {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Aggregates: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Aggregates: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Piece (cid.Cid) (struct)
	if len("piece") > 8192 {
		return fmt.Errorf("string in field \"piece\" was too long")
	}
	if err := jw.WriteString(string("piece")); err != nil {
		return fmt.Errorf("writing string for field \"piece\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Piece); err != nil {
		return fmt.Errorf("writing CID for field t.Piece: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *InfoOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = InfoOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for InfoOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for InfoOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for InfoOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field InfoOK: string too large")
				}
				return fmt.Errorf("reading string for field InfoOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field InfoOK: %w", err)
			}
			switch name {

			// t.Aggregates ([]pdp.InfoAcceptedAggregate) (slice)
			case "aggregates":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Aggregates: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Aggregates: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Aggregates: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]InfoAcceptedAggregate, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Aggregates = append(t.Aggregates, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Aggregates: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Aggregates: slice too large")
							}
						}
					}

				}

				// t.Piece (cid.Cid) (struct)
			case "piece":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Piece: %w", err)
					}
					t.Piece = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for InfoOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field InfoOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for InfoOK")
			}
		}
	}

	return nil
}
