//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package blob

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	promise "github.com/fil-forge/ucantone/ucan/promise"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *AllocateArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Blob (blob.Blob) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cause (cid.Cid) (struct)
	if len("cause") > 8192 {
		return fmt.Errorf("string in field \"cause\" was too long")
	}
	if err := jw.WriteString(string("cause")); err != nil {
		return fmt.Errorf("writing string for field \"cause\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Cause); err != nil {
		return fmt.Errorf("writing CID for field t.Cause: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Space (did.DID) (struct)
	if len("space") > 8192 {
		return fmt.Errorf("string in field \"space\" was too long")
	}
	if err := jw.WriteString(string("space")); err != nil {
		return fmt.Errorf("writing string for field \"space\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Space.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Space: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AllocateArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AllocateArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AllocateArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AllocateArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AllocateArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AllocateArguments: string too large")
				}
				return fmt.Errorf("reading string for field AllocateArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AllocateArguments: %w", err)
			}
			switch name {

			// t.Blob (blob.Blob) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.Cause (cid.Cid) (struct)
			case "cause":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Cause: %w", err)
					}
					t.Cause = c

				}

				// t.Space (did.DID) (struct)
			case "space":

				if err := t.Space.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Space: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AllocateArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AllocateArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AllocateArguments")
			}
		}
	}

	return nil
}
func (t *Blob) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("string in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("writing string for field \"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("writing bytes for field t.Digest: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return fmt.Errorf("string in field \"size\" was too long")
	}
	if err := jw.WriteString(string("size")); err != nil {
		return fmt.Errorf("writing string for field \"size\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Size)); err != nil {
		return fmt.Errorf("writing uint64 for field t.Size: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Blob) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Blob{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Blob: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Blob: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Blob: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Blob: string too large")
				}
				return fmt.Errorf("reading string for field Blob: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Blob: %w", err)
			}
			switch name {

			// t.Digest (multihash.Multihash) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Digest: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

				// t.Size (uint64) (uint64)
			case "size":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.Size: %w", err)
					}
					t.Size = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Blob: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Blob: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Blob")
			}
		}
	}

	return nil
}
func (t *AllocateOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Address (blob.BlobAddress) (struct)
	if t.Address != nil {
		if len("address") > 8192 {
			return fmt.Errorf("string in field \"address\" was too long")
		}
		if err := jw.WriteString(string("address")); err != nil {
			return fmt.Errorf("writing string for field \"address\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.Address.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field t.Address: %w", err)
		}
		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return fmt.Errorf("string in field \"size\" was too long")
	}
	if err := jw.WriteString(string("size")); err != nil {
		return fmt.Errorf("writing string for field \"size\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Size)); err != nil {
		return fmt.Errorf("writing uint64 for field t.Size: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AllocateOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AllocateOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AllocateOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AllocateOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AllocateOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AllocateOK: string too large")
				}
				return fmt.Errorf("reading string for field AllocateOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AllocateOK: %w", err)
			}
			switch name {

			// t.Address (blob.BlobAddress) (struct)
			case "address":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("peeking null for field t.Address: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("reading null for field t.Address: %w", err)
						}
					} else {
						t.Address = new(BlobAddress)
						if err := t.Address.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Address pointer: %w", err)
						}
					}
				}

				// t.Size (uint64) (uint64)
			case "size":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.Size: %w", err)
					}
					t.Size = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AllocateOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AllocateOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AllocateOK")
			}
		}
	}

	return nil
}
func (t *BlobAddress) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Expires (int64) (int64)
	if len("expires") > 8192 {
		return fmt.Errorf("string in field \"expires\" was too long")
	}
	if err := jw.WriteString(string("expires")); err != nil {
		return fmt.Errorf("writing string for field \"expires\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Expires)); err != nil {
		return fmt.Errorf("writing int64 for field t.Expires: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Headers (map[string]string) (map)
	if len("headers") > 8192 {
		return fmt.Errorf("string in field \"headers\" was too long")
	}
	if err := jw.WriteString(string("headers")); err != nil {
		return fmt.Errorf("writing string for field \"headers\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Headers) > 4096 {
			return fmt.Errorf("cannot marshal t.Headers map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Headers: %w", err)
		}

		keys := make([]string, 0, len(t.Headers))
		for k := range t.Headers {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Headers: %w", err)
				}
			}
			v := t.Headers[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Headers: %w", err)
			}

			if len(v) > 8192 {
				return fmt.Errorf("string in field v was too long")
			}
			if err := jw.WriteString(string(v)); err != nil {
				return fmt.Errorf("writing string for field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Headers: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.URL (commands.CborURL) (struct)
	if len("url") > 8192 {
		return fmt.Errorf("string in field \"url\" was too long")
	}
	if err := jw.WriteString(string("url")); err != nil {
		return fmt.Errorf("writing string for field \"url\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.URL.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.URL: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *BlobAddress) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BlobAddress{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for BlobAddress: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for BlobAddress: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for BlobAddress: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field BlobAddress: string too large")
				}
				return fmt.Errorf("reading string for field BlobAddress: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field BlobAddress: %w", err)
			}
			switch name {

			// t.Expires (int64) (int64)
			case "expires":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Expires: %w", err)
					}
					t.Expires = int64(nval)

				}

				// t.Headers (map[string]string) (map)
			case "headers":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Headers: %w", err)
				}

				t.Headers = map[string]string{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Headers: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Headers: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Headers: %w", err)
						}
						var v string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field v: string too long")
								}
								return fmt.Errorf("reading string for field v: %w", err)
							}
							v = string(sval)
						}
						t.Headers[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Headers: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.URL (commands.CborURL) (struct)
			case "url":

				if err := t.URL.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.URL: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for BlobAddress: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field BlobAddress: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for BlobAddress")
			}
		}
	}

	return nil
}
func (t *AcceptArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Put (promise.AwaitOK) (struct)
	if len("_put") > 8192 {
		return fmt.Errorf("string in field \"_put\" was too long")
	}
	if err := jw.WriteString(string("_put")); err != nil {
		return fmt.Errorf("writing string for field \"_put\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Put.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Put: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Blob (blob.Blob) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Space (did.DID) (struct)
	if len("space") > 8192 {
		return fmt.Errorf("string in field \"space\" was too long")
	}
	if err := jw.WriteString(string("space")); err != nil {
		return fmt.Errorf("writing string for field \"space\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Space.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Space: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AcceptArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AcceptArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AcceptArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AcceptArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AcceptArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AcceptArguments: string too large")
				}
				return fmt.Errorf("reading string for field AcceptArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AcceptArguments: %w", err)
			}
			switch name {

			// t.Put (promise.AwaitOK) (struct)
			case "_put":

				if err := t.Put.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Put: %w", err)
				}

				// t.Blob (blob.Blob) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.Space (did.DID) (struct)
			case "space":

				if err := t.Space.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Space: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AcceptArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AcceptArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AcceptArguments")
			}
		}
	}

	return nil
}
func (t *AcceptOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.PDP (promise.AwaitOK) (struct)
	if len("pdp") > 8192 {
		return fmt.Errorf("string in field \"pdp\" was too long")
	}
	if err := jw.WriteString(string("pdp")); err != nil {
		return fmt.Errorf("writing string for field \"pdp\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.PDP.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.PDP: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Site (cid.Cid) (struct)
	if len("site") > 8192 {
		return fmt.Errorf("string in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("writing string for field \"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Site); err != nil {
		return fmt.Errorf("writing CID for field t.Site: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AcceptOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AcceptOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AcceptOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AcceptOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AcceptOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AcceptOK: string too large")
				}
				return fmt.Errorf("reading string for field AcceptOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AcceptOK: %w", err)
			}
			switch name {

			// t.PDP (promise.AwaitOK) (struct)
			case "pdp":

				if err := t.PDP.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.PDP: %w", err)
				}

				// t.Site (cid.Cid) (struct)
			case "site":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Site: %w", err)
					}
					t.Site = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AcceptOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AcceptOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AcceptOK")
			}
		}
	}

	return nil
}
func (t *AddArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Blob (blob.Blob) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AddArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AddArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AddArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AddArguments: string too large")
				}
				return fmt.Errorf("reading string for field AddArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AddArguments: %w", err)
			}
			switch name {

			// t.Blob (blob.Blob) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AddArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AddArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AddArguments")
			}
		}
	}

	return nil
}
func (t *AddOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Site (promise.AwaitOK) (struct)
	if len("site") > 8192 {
		return fmt.Errorf("string in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("writing string for field \"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Site.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Site: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AddOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AddOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AddOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AddOK: string too large")
				}
				return fmt.Errorf("reading string for field AddOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AddOK: %w", err)
			}
			switch name {

			// t.Site (promise.AwaitOK) (struct)
			case "site":

				if err := t.Site.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Site: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AddOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AddOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AddOK")
			}
		}
	}

	return nil
}
func (t *RemoveArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("string in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("writing string for field \"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("writing bytes for field t.Digest: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Space (did.DID) (struct)
	if len("space") > 8192 {
		return fmt.Errorf("string in field \"space\" was too long")
	}
	if err := jw.WriteString(string("space")); err != nil {
		return fmt.Errorf("writing string for field \"space\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Space.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Space: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RemoveArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RemoveArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RemoveArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RemoveArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RemoveArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RemoveArguments: string too large")
				}
				return fmt.Errorf("reading string for field RemoveArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RemoveArguments: %w", err)
			}
			switch name {

			// t.Digest (multihash.Multihash) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Digest: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

				// t.Space (did.DID) (struct)
			case "space":

				if err := t.Space.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Space: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RemoveArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RemoveArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RemoveArguments")
			}
		}
	}

	return nil
}
func (t *ReplicateArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Blob (blob.Blob) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Replicas (uint64) (uint64)
	if len("replicas") > 8192 {
		return fmt.Errorf("string in field \"replicas\" was too long")
	}
	if err := jw.WriteString(string("replicas")); err != nil {
		return fmt.Errorf("writing string for field \"replicas\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Replicas)); err != nil {
		return fmt.Errorf("writing uint64 for field t.Replicas: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Site (cid.Cid) (struct)
	if len("site") > 8192 {
		return fmt.Errorf("string in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("writing string for field \"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Site); err != nil {
		return fmt.Errorf("writing CID for field t.Site: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ReplicateArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ReplicateArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ReplicateArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ReplicateArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ReplicateArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ReplicateArguments: string too large")
				}
				return fmt.Errorf("reading string for field ReplicateArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ReplicateArguments: %w", err)
			}
			switch name {

			// t.Blob (blob.Blob) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.Replicas (uint64) (uint64)
			case "replicas":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.Replicas: %w", err)
					}
					t.Replicas = uint64(nval)

				}

				// t.Site (cid.Cid) (struct)
			case "site":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Site: %w", err)
					}
					t.Site = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ReplicateArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ReplicateArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ReplicateArguments")
			}
		}
	}

	return nil
}
func (t *ReplicateOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Site ([]promise.AwaitOK) (slice)
	if len("site") > 8192 {
		return fmt.Errorf("string in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("writing string for field \"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Site) > 8192 {
		return fmt.Errorf("slice value in field t.Site was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Site: %w", err)
	}
	for i, v := range t.Site {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Site: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Site: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ReplicateOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ReplicateOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ReplicateOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ReplicateOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ReplicateOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ReplicateOK: string too large")
				}
				return fmt.Errorf("reading string for field ReplicateOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ReplicateOK: %w", err)
			}
			switch name {

			// t.Site ([]promise.AwaitOK) (slice)
			case "site":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Site: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Site: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Site: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]promise.AwaitOK, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Site = append(t.Site, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Site: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Site: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ReplicateOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ReplicateOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ReplicateOK")
			}
		}
	}

	return nil
}
func (t *ListArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Cursor (string) (string)
	if t.Cursor != nil {
		if len("cursor") > 8192 {
			return fmt.Errorf("string in field \"cursor\" was too long")
		}
		if err := jw.WriteString(string("cursor")); err != nil {
			return fmt.Errorf("writing string for field \"cursor\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if t.Cursor == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("writing null for field t.Cursor: %w", err)
			}
		} else {
			if len(*t.Cursor) > 8192 {
				return fmt.Errorf("string in field t.Cursor was too long")
			}
			if err := jw.WriteString(string(*t.Cursor)); err != nil {
				return fmt.Errorf("writing string for field t.Cursor: %w", err)
			}
		}
		written++
	}
	if t.Size != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Size (uint64) (uint64)
	if t.Size != nil {
		if len("size") > 8192 {
			return fmt.Errorf("string in field \"size\" was too long")
		}
		if err := jw.WriteString(string("size")); err != nil {
			return fmt.Errorf("writing string for field \"size\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}

		if t.Size == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("writing null for field t.Size: %w", err)
			}
		} else {
			if err := jw.WriteUint64(uint64(*t.Size)); err != nil {
				return fmt.Errorf("writing uint64 for field t.Size: %w", err)
			}
		}

		written++
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ListArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ListArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ListArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ListArguments: string too large")
				}
				return fmt.Errorf("reading string for field ListArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ListArguments: %w", err)
			}
			switch name {

			// t.Cursor (string) (string)
			case "cursor":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string or null for field t.Cursor: string too long")
						}
						return fmt.Errorf("reading string or null for field t.Cursor: %w", err)
					}
					if sval != nil {
						t.Cursor = (*string)(sval)
					}
				}

				// t.Size (uint64) (uint64)
			case "size":
				{

					nval, err := jr.ReadNumberAsUint64OrNull()
					if err != nil {
						return fmt.Errorf("reading uint64 or null for field t.Size: %w", err)
					}
					if nval != nil {
						typed := uint64(*nval)
						t.Size = &typed
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ListArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ListArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ListArguments")
			}
		}
	}

	return nil
}
func (t *ListOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Cursor (string) (string)
	if t.Cursor != nil {
		if len("cursor") > 8192 {
			return fmt.Errorf("string in field \"cursor\" was too long")
		}
		if err := jw.WriteString(string("cursor")); err != nil {
			return fmt.Errorf("writing string for field \"cursor\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if t.Cursor == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("writing null for field t.Cursor: %w", err)
			}
		} else {
			if len(*t.Cursor) > 8192 {
				return fmt.Errorf("string in field t.Cursor was too long")
			}
			if err := jw.WriteString(string(*t.Cursor)); err != nil {
				return fmt.Errorf("writing string for field t.Cursor: %w", err)
			}
		}
		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Results ([]blob.ListBlobItem) (slice)
	if len("results") > 8192 {
		return fmt.Errorf("string in field \"results\" was too long")
	}
	if err := jw.WriteString(string("results")); err != nil {
		return fmt.Errorf("writing string for field \"results\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Results) > 8192 {
		return fmt.Errorf("slice value in field t.Results was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Results: %w", err)
	}
	for i, v := range t.Results {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Results: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Results: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return fmt.Errorf("string in field \"size\" was too long")
	}
	if err := jw.WriteString(string("size")); err != nil {
		return fmt.Errorf("writing string for field \"size\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Size)); err != nil {
		return fmt.Errorf("writing uint64 for field t.Size: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ListOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ListOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ListOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ListOK: string too large")
				}
				return fmt.Errorf("reading string for field ListOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ListOK: %w", err)
			}
			switch name {

			// t.Cursor (string) (string)
			case "cursor":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string or null for field t.Cursor: string too long")
						}
						return fmt.Errorf("reading string or null for field t.Cursor: %w", err)
					}
					if sval != nil {
						t.Cursor = (*string)(sval)
					}
				}

				// t.Results ([]blob.ListBlobItem) (slice)
			case "results":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Results: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Results: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Results: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]ListBlobItem, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Results = append(t.Results, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Results: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Results: slice too large")
							}
						}
					}

				}

				// t.Size (uint64) (uint64)
			case "size":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.Size: %w", err)
					}
					t.Size = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ListOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ListOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ListOK")
			}
		}
	}

	return nil
}
func (t *ListBlobItem) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Blob (blob.Blob) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.InsertedAt (int64) (int64)
	if len("insertedAt") > 8192 {
		return fmt.Errorf("string in field \"insertedAt\" was too long")
	}
	if err := jw.WriteString(string("insertedAt")); err != nil {
		return fmt.Errorf("writing string for field \"insertedAt\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.InsertedAt)); err != nil {
		return fmt.Errorf("writing int64 for field t.InsertedAt: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListBlobItem) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListBlobItem{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ListBlobItem: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ListBlobItem: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ListBlobItem: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ListBlobItem: string too large")
				}
				return fmt.Errorf("reading string for field ListBlobItem: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ListBlobItem: %w", err)
			}
			switch name {

			// t.Blob (blob.Blob) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.InsertedAt (int64) (int64)
			case "insertedAt":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.InsertedAt: %w", err)
					}
					t.InsertedAt = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ListBlobItem: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ListBlobItem: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ListBlobItem")
			}
		}
	}

	return nil
}
func (t *RetrieveArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Blob (blob.RetrieveBlob) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RetrieveArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RetrieveArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RetrieveArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RetrieveArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RetrieveArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RetrieveArguments: string too large")
				}
				return fmt.Errorf("reading string for field RetrieveArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RetrieveArguments: %w", err)
			}
			switch name {

			// t.Blob (blob.RetrieveBlob) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RetrieveArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RetrieveArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RetrieveArguments")
			}
		}
	}

	return nil
}
func (t *RetrieveBlob) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("string in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("writing string for field \"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("writing bytes for field t.Digest: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RetrieveBlob) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RetrieveBlob{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RetrieveBlob: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RetrieveBlob: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RetrieveBlob: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RetrieveBlob: string too large")
				}
				return fmt.Errorf("reading string for field RetrieveBlob: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RetrieveBlob: %w", err)
			}
			switch name {

			// t.Digest (multihash.Multihash) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Digest: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RetrieveBlob: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RetrieveBlob: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RetrieveBlob")
			}
		}
	}

	return nil
}
func (t *RetrieveOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RetrieveOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RetrieveOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RetrieveOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RetrieveOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RetrieveOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RetrieveOK: string too large")
				}
				return fmt.Errorf("reading string for field RetrieveOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RetrieveOK: %w", err)
			}
			switch name {
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RetrieveOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RetrieveOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RetrieveOK")
			}
		}
	}

	return nil
}
