//go:build !codegen

// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package assert

import (
	"fmt"
	"io"
	"math"
	"sort"

	capabilities "github.com/fil-forge/libforge/capabilities"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *IndexArguments) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.Index (cid.Cid) (struct)
	if len("index") > 8192 {
		return xerrors.Errorf("Value in field \"index\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("index"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("index")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.Index); err != nil {
		return xerrors.Errorf("failed to write cid field t.Index: %w", err)
	}

	return nil
}

func (t *IndexArguments) UnmarshalCBOR(r io.Reader) (err error) {
	*t = IndexArguments{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("IndexArguments: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 5)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Index (cid.Cid) (struct)
		case "index":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.Index: %w", err)
				}

				t.Index = c

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *LocationArguments) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 4

	if t.Range == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Range (assert.Range) (struct)
	if t.Range != nil {

		if len("range") > 8192 {
			return xerrors.Errorf("Value in field \"range\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("range"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("range")); err != nil {
			return err
		}

		if err := t.Range.MarshalCBOR(cw); err != nil {
			return err
		}
	}

	// t.Space (did.DID) (struct)
	if len("space") > 8192 {
		return xerrors.Errorf("Value in field \"space\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("space"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("space")); err != nil {
		return err
	}

	if err := t.Space.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Content (multihash.Multihash) (slice)
	if len("content") > 8192 {
		return xerrors.Errorf("Value in field \"content\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("content"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("content")); err != nil {
		return err
	}

	if len(t.Content) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Content was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Content))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Content); err != nil {
		return err
	}

	// t.Location ([]capabilities.CborURL) (slice)
	if len("location") > 8192 {
		return xerrors.Errorf("Value in field \"location\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("location"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("location")); err != nil {
		return err
	}

	if len(t.Location) > 8192 {
		return xerrors.Errorf("Slice value in field t.Location was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Location))); err != nil {
		return err
	}
	for _, v := range t.Location {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}
	return nil
}

func (t *LocationArguments) UnmarshalCBOR(r io.Reader) (err error) {
	*t = LocationArguments{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("LocationArguments: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Range (assert.Range) (struct)
		case "range":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.Range = new(Range)
					if err := t.Range.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.Range pointer: %w", err)
					}
				}

			}
			// t.Space (did.DID) (struct)
		case "space":

			{

				if err := t.Space.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Space: %w", err)
				}

			}
			// t.Content (multihash.Multihash) (slice)
		case "content":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Content: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Content = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Content); err != nil {
				return err
			}

			// t.Location ([]capabilities.CborURL) (slice)
		case "location":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Location: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Location = make([]capabilities.CborURL, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						if err := t.Location[i].UnmarshalCBOR(cr); err != nil {
							return xerrors.Errorf("unmarshaling t.Location[i]: %w", err)
						}

					}

				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *Range) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 2

	if t.Length == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Length (uint64) (uint64)
	if t.Length != nil {

		if len("length") > 8192 {
			return xerrors.Errorf("Value in field \"length\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("length"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("length")); err != nil {
			return err
		}

		if t.Length == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(*t.Length)); err != nil {
				return err
			}
		}

	}

	// t.Offset (uint64) (uint64)
	if len("offset") > 8192 {
		return xerrors.Errorf("Value in field \"offset\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("offset"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("offset")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Offset)); err != nil {
		return err
	}

	return nil
}

func (t *Range) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Range{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Range: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 6)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Length (uint64) (uint64)
		case "length":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					maj, extra, err = cr.ReadHeader()
					if err != nil {
						return err
					}
					if maj != cbg.MajUnsignedInt {
						return fmt.Errorf("wrong type for uint64 field")
					}
					typed := uint64(extra)
					t.Length = &typed
				}

			}
			// t.Offset (uint64) (uint64)
		case "offset":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.Offset = uint64(extra)

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *EqualsArguments) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Equals (cid.Cid) (struct)
	if len("equals") > 8192 {
		return xerrors.Errorf("Value in field \"equals\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("equals"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("equals")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.Equals); err != nil {
		return xerrors.Errorf("failed to write cid field t.Equals: %w", err)
	}

	// t.Content (multihash.Multihash) (slice)
	if len("content") > 8192 {
		return xerrors.Errorf("Value in field \"content\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("content"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("content")); err != nil {
		return err
	}

	if len(t.Content) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Content was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Content))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Content); err != nil {
		return err
	}

	return nil
}

func (t *EqualsArguments) UnmarshalCBOR(r io.Reader) (err error) {
	*t = EqualsArguments{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("EqualsArguments: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 7)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Equals (cid.Cid) (struct)
		case "equals":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.Equals: %w", err)
				}

				t.Equals = c

			}
			// t.Content (multihash.Multihash) (slice)
		case "content":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Content: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Content = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Content); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
