//go:build !codegen

// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package customer

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *AddArguments) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 4

	if t.Account == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Account (string) (string)
	if t.Account != nil {

		if len("account") > 8192 {
			return xerrors.Errorf("Value in field \"account\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("account"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("account")); err != nil {
			return err
		}

		if t.Account == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Account) > 8192 {
				return xerrors.Errorf("Value in field t.Account was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Account))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Account)); err != nil {
				return err
			}
		}
	}

	// t.Details (map[string]string) (map)
	if len("details") > 8192 {
		return xerrors.Errorf("Value in field \"details\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("details"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("details")); err != nil {
		return err
	}

	{
		if len(t.Details) > 4096 {
			return xerrors.Errorf("cannot marshal t.Details map too large")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajMap, uint64(len(t.Details))); err != nil {
			return err
		}

		keys := make([]string, 0, len(t.Details))
		for k := range t.Details {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := t.Details[k]

			if len(k) > 8192 {
				return xerrors.Errorf("Value in field k was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(k))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(k)); err != nil {
				return err
			}

			if len(v) > 8192 {
				return xerrors.Errorf("Value in field v was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(v))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(v)); err != nil {
				return err
			}

		}
	}

	// t.Product (did.DID) (struct)
	if len("product") > 8192 {
		return xerrors.Errorf("Value in field \"product\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("product"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("product")); err != nil {
		return err
	}

	if err := t.Product.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Customer (did.DID) (struct)
	if len("customer") > 8192 {
		return xerrors.Errorf("Value in field \"customer\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("customer"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("customer")); err != nil {
		return err
	}

	if err := t.Customer.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *AddArguments) UnmarshalCBOR(r io.Reader) (err error) {
	*t = AddArguments{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("AddArguments: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Account (string) (string)
		case "account":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					t.Account = (*string)(&sval)
				}
			}
			// t.Details (map[string]string) (map)
		case "details":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajMap {
				return fmt.Errorf("expected a map (major type 5)")
			}
			if extra > 4096 {
				return fmt.Errorf("t.Details: map too large")
			}

			t.Details = make(map[string]string, extra)

			for i, l := 0, int(extra); i < l; i++ {

				var k string

				{
					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					k = string(sval)
				}

				var v string

				{
					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					v = string(sval)
				}

				t.Details[k] = v

			}
			// t.Product (did.DID) (struct)
		case "product":

			{

				if err := t.Product.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Product: %w", err)
				}

			}
			// t.Customer (did.DID) (struct)
		case "customer":

			{

				if err := t.Customer.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Customer: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
