// Package routing defines the routing policy UCAN commands served by the
// upload service. A routing policy is a did:key that owns a set of storage
// node DIDs (its candidates). A space that references a policy has every
// `/blob/add` routed to one of the policy's candidates, whoever invoked the
// write.
//
// CandidateSet is a DID-keyed map. cbor-gen / dag-json-gen only generate
// string-keyed maps, so it has a hand-written codec (see codec.go) and is
// defined as a struct wrapping the map so that structs embedding it can still
// be generated as usual.
package routing

import "github.com/fil-forge/ucantone/did"

// Candidate holds the per-node properties of a routing policy candidate. It is
// currently empty and reserved for properties that influence routing decisions
// (e.g. weight).
type Candidate struct{}

// CandidateSet maps a storage node DID to its [Candidate] properties. The map
// is a set: encoding is unordered and dag-cbor sorts the keys. The DID is
// encoded as the (string) map key on the wire.
//
// It is a struct wrapping the map (rather than a named map type) so that
// structs embedding it can be generated by cbor-gen / dag-json-gen, which
// delegate to a struct field's MarshalCBOR but cannot generate a DID-keyed map
// inline. On the wire it encodes as the bare map, not as an object with an
// "entries" key.
type CandidateSet struct {
	Entries map[did.DID]Candidate
}

// PutArguments are the arguments to the `/routing/put` command.
type PutArguments struct {
	// Candidates is the complete candidate set of the policy. It replaces any
	// previously stored set and MUST contain at least one entry.
	Candidates CandidateSet `cborgen:"candidates" dagjsongen:"candidates"`
}

// UseArguments are the arguments to the `/routing/use` command.
type UseArguments struct {
	// Policy is the DID of the routing policy the space should use. When
	// absent the space's policy reference is cleared and the space returns to
	// default routing.
	Policy *did.DID `cborgen:"policy,omitempty" dagjsongen:"policy,omitempty"`
}
