// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package datamodel

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *AuthSignatureModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{166}); err != nil {
		return err
	}

	// t.R ([]uint8) (slice)
	if len("r") > 8192 {
		return xerrors.Errorf("Value in field \"r\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("r"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("r")); err != nil {
		return err
	}

	if len(t.R) > 2097152 {
		return xerrors.Errorf("Byte array in field t.R was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.R))); err != nil {
		return err
	}

	if _, err := cw.Write(t.R); err != nil {
		return err
	}

	// t.S ([]uint8) (slice)
	if len("s") > 8192 {
		return xerrors.Errorf("Value in field \"s\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("s"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("s")); err != nil {
		return err
	}

	if len(t.S) > 2097152 {
		return xerrors.Errorf("Byte array in field t.S was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.S))); err != nil {
		return err
	}

	if _, err := cw.Write(t.S); err != nil {
		return err
	}

	// t.V (uint8) (uint8)
	if len("v") > 8192 {
		return xerrors.Errorf("Value in field \"v\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("v"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("v")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.V)); err != nil {
		return err
	}

	// t.Signer ([]uint8) (slice)
	if len("signer") > 8192 {
		return xerrors.Errorf("Value in field \"signer\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("signer"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("signer")); err != nil {
		return err
	}

	if len(t.Signer) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Signer was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Signer))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Signer); err != nil {
		return err
	}

	// t.Signature ([]uint8) (slice)
	if len("signature") > 8192 {
		return xerrors.Errorf("Value in field \"signature\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("signature"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("signature")); err != nil {
		return err
	}

	if len(t.Signature) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Signature was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Signature))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Signature); err != nil {
		return err
	}

	// t.SignedData ([]uint8) (slice)
	if len("signedData") > 8192 {
		return xerrors.Errorf("Value in field \"signedData\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("signedData"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("signedData")); err != nil {
		return err
	}

	if len(t.SignedData) > 2097152 {
		return xerrors.Errorf("Byte array in field t.SignedData was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.SignedData))); err != nil {
		return err
	}

	if _, err := cw.Write(t.SignedData); err != nil {
		return err
	}

	return nil
}

func (t *AuthSignatureModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = AuthSignatureModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("AuthSignatureModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 10)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.R ([]uint8) (slice)
		case "r":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.R: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.R = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.R); err != nil {
				return err
			}

			// t.S ([]uint8) (slice)
		case "s":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.S: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.S = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.S); err != nil {
				return err
			}

			// t.V (uint8) (uint8)
		case "v":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajUnsignedInt {
				return fmt.Errorf("wrong type for uint8 field")
			}
			if extra > math.MaxUint8 {
				return fmt.Errorf("integer in input was too large for uint8 field")
			}
			t.V = uint8(extra)
			// t.Signer ([]uint8) (slice)
		case "signer":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Signer: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Signer = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Signer); err != nil {
				return err
			}

			// t.Signature ([]uint8) (slice)
		case "signature":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Signature: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Signature = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Signature); err != nil {
				return err
			}

			// t.SignedData ([]uint8) (slice)
		case "signedData":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.SignedData: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.SignedData = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.SignedData); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *MetadataModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Keys ([]string) (slice)
	if len("keys") > 8192 {
		return xerrors.Errorf("Value in field \"keys\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("keys"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("keys")); err != nil {
		return err
	}

	if len(t.Keys) > 8192 {
		return xerrors.Errorf("Slice value in field t.Keys was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Keys))); err != nil {
		return err
	}
	for _, v := range t.Keys {
		if len(v) > 8192 {
			return xerrors.Errorf("Value in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(v))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string(v)); err != nil {
			return err
		}

	}

	// t.Values (map[string]string) (map)
	if len("values") > 8192 {
		return xerrors.Errorf("Value in field \"values\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("values"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("values")); err != nil {
		return err
	}

	{
		if len(t.Values) > 4096 {
			return xerrors.Errorf("cannot marshal t.Values map too large")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajMap, uint64(len(t.Values))); err != nil {
			return err
		}

		keys := make([]string, 0, len(t.Values))
		for k := range t.Values {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := t.Values[k]

			if len(k) > 8192 {
				return xerrors.Errorf("Value in field k was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(k))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(k)); err != nil {
				return err
			}

			if len(v) > 8192 {
				return xerrors.Errorf("Value in field v was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(v))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(v)); err != nil {
				return err
			}

		}
	}
	return nil
}

func (t *MetadataModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = MetadataModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("MetadataModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 6)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Keys ([]string) (slice)
		case "keys":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Keys: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Keys = make([]string, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{
						sval, err := cbg.ReadStringWithMax(cr, 8192)
						if err != nil {
							return err
						}

						t.Keys[i] = string(sval)
					}

				}
			}
			// t.Values (map[string]string) (map)
		case "values":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajMap {
				return fmt.Errorf("expected a map (major type 5)")
			}
			if extra > 4096 {
				return fmt.Errorf("t.Values: map too large")
			}

			t.Values = make(map[string]string, extra)

			for i, l := 0, int(extra); i < l; i++ {

				var k string

				{
					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					k = string(sval)
				}

				var v string

				{
					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					v = string(sval)
				}

				t.Values[k] = v

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *PieceProofsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.Proofs ([]cid.Cid) (slice)
	if len("proofs") > 8192 {
		return xerrors.Errorf("Value in field \"proofs\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("proofs"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("proofs")); err != nil {
		return err
	}

	if len(t.Proofs) > 8192 {
		return xerrors.Errorf("Slice value in field t.Proofs was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Proofs))); err != nil {
		return err
	}
	for _, v := range t.Proofs {

		if err := cbg.WriteCid(cw, v); err != nil {
			return xerrors.Errorf("failed to write cid field v: %w", err)
		}

	}
	return nil
}

func (t *PieceProofsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = PieceProofsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("PieceProofsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 6)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Proofs ([]cid.Cid) (slice)
		case "proofs":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Proofs: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Proofs = make([]cid.Cid, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						c, err := cbg.ReadCid(cr)
						if err != nil {
							return xerrors.Errorf("failed to read cid field t.Proofs[i]: %w", err)
						}

						t.Proofs[i] = c

					}

				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *DataSetCreateArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{163}); err != nil {
		return err
	}

	// t.Payee ([]uint8) (slice)
	if len("payee") > 8192 {
		return xerrors.Errorf("Value in field \"payee\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("payee"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("payee")); err != nil {
		return err
	}

	if len(t.Payee) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Payee was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Payee))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Payee); err != nil {
		return err
	}

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return xerrors.Errorf("Value in field \"dataSet\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("dataSet"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("dataSet")); err != nil {
		return err
	}

	if len(t.DataSet) > 2097152 {
		return xerrors.Errorf("Byte array in field t.DataSet was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.DataSet))); err != nil {
		return err
	}

	if _, err := cw.Write(t.DataSet); err != nil {
		return err
	}

	// t.Metadata (datamodel.MetadataModel) (struct)
	if len("metadata") > 8192 {
		return xerrors.Errorf("Value in field \"metadata\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("metadata"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("metadata")); err != nil {
		return err
	}

	if err := t.Metadata.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *DataSetCreateArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = DataSetCreateArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("DataSetCreateArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Payee ([]uint8) (slice)
		case "payee":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Payee: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Payee = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Payee); err != nil {
				return err
			}

			// t.DataSet ([]uint8) (slice)
		case "dataSet":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.DataSet: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.DataSet = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.DataSet); err != nil {
				return err
			}

			// t.Metadata (datamodel.MetadataModel) (struct)
		case "metadata":

			{

				if err := t.Metadata.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Metadata: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *DataSetDeleteArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return xerrors.Errorf("Value in field \"dataSet\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("dataSet"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("dataSet")); err != nil {
		return err
	}

	if len(t.DataSet) > 2097152 {
		return xerrors.Errorf("Byte array in field t.DataSet was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.DataSet))); err != nil {
		return err
	}

	if _, err := cw.Write(t.DataSet); err != nil {
		return err
	}

	return nil
}

func (t *DataSetDeleteArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = DataSetDeleteArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("DataSetDeleteArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 7)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.DataSet ([]uint8) (slice)
		case "dataSet":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.DataSet: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.DataSet = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.DataSet); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *PiecesAddArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{165}); err != nil {
		return err
	}

	// t.Nonce ([]uint8) (slice)
	if len("nonce") > 8192 {
		return xerrors.Errorf("Value in field \"nonce\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("nonce"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("nonce")); err != nil {
		return err
	}

	if len(t.Nonce) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Nonce was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Nonce))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Nonce); err != nil {
		return err
	}

	// t.Proofs ([]datamodel.PieceProofsModel) (slice)
	if len("proofs") > 8192 {
		return xerrors.Errorf("Value in field \"proofs\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("proofs"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("proofs")); err != nil {
		return err
	}

	if len(t.Proofs) > 8192 {
		return xerrors.Errorf("Slice value in field t.Proofs was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Proofs))); err != nil {
		return err
	}
	for _, v := range t.Proofs {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return xerrors.Errorf("Value in field \"dataSet\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("dataSet"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("dataSet")); err != nil {
		return err
	}

	if len(t.DataSet) > 2097152 {
		return xerrors.Errorf("Byte array in field t.DataSet was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.DataSet))); err != nil {
		return err
	}

	if _, err := cw.Write(t.DataSet); err != nil {
		return err
	}

	// t.Metadata ([]datamodel.MetadataModel) (slice)
	if len("metadata") > 8192 {
		return xerrors.Errorf("Value in field \"metadata\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("metadata"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("metadata")); err != nil {
		return err
	}

	if len(t.Metadata) > 8192 {
		return xerrors.Errorf("Slice value in field t.Metadata was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Metadata))); err != nil {
		return err
	}
	for _, v := range t.Metadata {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}

	// t.PieceData ([][]uint8) (slice)
	if len("pieceData") > 8192 {
		return xerrors.Errorf("Value in field \"pieceData\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("pieceData"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("pieceData")); err != nil {
		return err
	}

	if len(t.PieceData) > 8192 {
		return xerrors.Errorf("Slice value in field t.PieceData was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.PieceData))); err != nil {
		return err
	}
	for _, v := range t.PieceData {
		if len(v) > 2097152 {
			return xerrors.Errorf("Byte array in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(v))); err != nil {
			return err
		}

		if _, err := cw.Write(v); err != nil {
			return err
		}

	}
	return nil
}

func (t *PiecesAddArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = PiecesAddArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("PiecesAddArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 9)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Nonce ([]uint8) (slice)
		case "nonce":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Nonce: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Nonce = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Nonce); err != nil {
				return err
			}

			// t.Proofs ([]datamodel.PieceProofsModel) (slice)
		case "proofs":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Proofs: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Proofs = make([]PieceProofsModel, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						if err := t.Proofs[i].UnmarshalCBOR(cr); err != nil {
							return xerrors.Errorf("unmarshaling t.Proofs[i]: %w", err)
						}

					}

				}
			}
			// t.DataSet ([]uint8) (slice)
		case "dataSet":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.DataSet: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.DataSet = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.DataSet); err != nil {
				return err
			}

			// t.Metadata ([]datamodel.MetadataModel) (slice)
		case "metadata":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Metadata: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Metadata = make([]MetadataModel, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						if err := t.Metadata[i].UnmarshalCBOR(cr); err != nil {
							return xerrors.Errorf("unmarshaling t.Metadata[i]: %w", err)
						}

					}

				}
			}
			// t.PieceData ([][]uint8) (slice)
		case "pieceData":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.PieceData: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.PieceData = make([][]uint8, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					maj, extra, err = cr.ReadHeader()
					if err != nil {
						return err
					}

					if extra > 2097152 {
						return fmt.Errorf("t.PieceData[i]: byte array too large (%d)", extra)
					}
					if maj != cbg.MajByteString {
						return fmt.Errorf("expected byte array")
					}

					if extra > 0 {
						t.PieceData[i] = make([]uint8, extra)
					}

					if _, err := io.ReadFull(cr, t.PieceData[i]); err != nil {
						return err
					}

				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *PiecesRemoveScheduleArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Pieces ([][]uint8) (slice)
	if len("pieces") > 8192 {
		return xerrors.Errorf("Value in field \"pieces\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("pieces"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("pieces")); err != nil {
		return err
	}

	if len(t.Pieces) > 8192 {
		return xerrors.Errorf("Slice value in field t.Pieces was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Pieces))); err != nil {
		return err
	}
	for _, v := range t.Pieces {
		if len(v) > 2097152 {
			return xerrors.Errorf("Byte array in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(v))); err != nil {
			return err
		}

		if _, err := cw.Write(v); err != nil {
			return err
		}

	}

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return xerrors.Errorf("Value in field \"dataSet\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("dataSet"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("dataSet")); err != nil {
		return err
	}

	if len(t.DataSet) > 2097152 {
		return xerrors.Errorf("Byte array in field t.DataSet was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.DataSet))); err != nil {
		return err
	}

	if _, err := cw.Write(t.DataSet); err != nil {
		return err
	}

	return nil
}

func (t *PiecesRemoveScheduleArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = PiecesRemoveScheduleArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("PiecesRemoveScheduleArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 7)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Pieces ([][]uint8) (slice)
		case "pieces":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Pieces: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Pieces = make([][]uint8, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					maj, extra, err = cr.ReadHeader()
					if err != nil {
						return err
					}

					if extra > 2097152 {
						return fmt.Errorf("t.Pieces[i]: byte array too large (%d)", extra)
					}
					if maj != cbg.MajByteString {
						return fmt.Errorf("expected byte array")
					}

					if extra > 0 {
						t.Pieces[i] = make([]uint8, extra)
					}

					if _, err := io.ReadFull(cr, t.Pieces[i]); err != nil {
						return err
					}

				}
			}
			// t.DataSet ([]uint8) (slice)
		case "dataSet":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.DataSet: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.DataSet = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.DataSet); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
