// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *AuthSignatureModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.R ([]uint8) (slice)
	if len("r") > 8192 {
		return fmt.Errorf("string in field \"r\" was too long")
	}
	if err := jw.WriteString(string("r")); err != nil {
		return fmt.Errorf("writing string for field \"r\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.R) > 2097152 {
		return fmt.Errorf("byte array in field t.R was too long")
	}

	if err := jw.WriteBytes(t.R); err != nil {
		return fmt.Errorf("writing bytes for field t.R: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.S ([]uint8) (slice)
	if len("s") > 8192 {
		return fmt.Errorf("string in field \"s\" was too long")
	}
	if err := jw.WriteString(string("s")); err != nil {
		return fmt.Errorf("writing string for field \"s\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.S) > 2097152 {
		return fmt.Errorf("byte array in field t.S was too long")
	}

	if err := jw.WriteBytes(t.S); err != nil {
		return fmt.Errorf("writing bytes for field t.S: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Signature ([]uint8) (slice)
	if len("signature") > 8192 {
		return fmt.Errorf("string in field \"signature\" was too long")
	}
	if err := jw.WriteString(string("signature")); err != nil {
		return fmt.Errorf("writing string for field \"signature\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Signature) > 2097152 {
		return fmt.Errorf("byte array in field t.Signature was too long")
	}

	if err := jw.WriteBytes(t.Signature); err != nil {
		return fmt.Errorf("writing bytes for field t.Signature: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.SignedData ([]uint8) (slice)
	if len("signedData") > 8192 {
		return fmt.Errorf("string in field \"signedData\" was too long")
	}
	if err := jw.WriteString(string("signedData")); err != nil {
		return fmt.Errorf("writing string for field \"signedData\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.SignedData) > 2097152 {
		return fmt.Errorf("byte array in field t.SignedData was too long")
	}

	if err := jw.WriteBytes(t.SignedData); err != nil {
		return fmt.Errorf("writing bytes for field t.SignedData: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Signer ([]uint8) (slice)
	if len("signer") > 8192 {
		return fmt.Errorf("string in field \"signer\" was too long")
	}
	if err := jw.WriteString(string("signer")); err != nil {
		return fmt.Errorf("writing string for field \"signer\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Signer) > 2097152 {
		return fmt.Errorf("byte array in field t.Signer was too long")
	}

	if err := jw.WriteBytes(t.Signer); err != nil {
		return fmt.Errorf("writing bytes for field t.Signer: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.V (uint8) (uint8)
	if len("v") > 8192 {
		return fmt.Errorf("string in field \"v\" was too long")
	}
	if err := jw.WriteString(string("v")); err != nil {
		return fmt.Errorf("writing string for field \"v\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := jw.WriteUint8(uint8(t.V)); err != nil {
		return fmt.Errorf("writing uint8 for field t.V: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AuthSignatureModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AuthSignatureModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AuthSignatureModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AuthSignatureModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AuthSignatureModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AuthSignatureModel: string too large")
				}
				return fmt.Errorf("reading string for field AuthSignatureModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AuthSignatureModel: %w", err)
			}
			switch name {

			// t.R ([]uint8) (slice)
			case "r":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.R: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.R: %w", err)
					}
					if len(bval) > 0 {
						t.R = []uint8(bval)
					}
				}

				// t.S ([]uint8) (slice)
			case "s":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.S: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.S: %w", err)
					}
					if len(bval) > 0 {
						t.S = []uint8(bval)
					}
				}

				// t.Signature ([]uint8) (slice)
			case "signature":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Signature: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Signature: %w", err)
					}
					if len(bval) > 0 {
						t.Signature = []uint8(bval)
					}
				}

				// t.SignedData ([]uint8) (slice)
			case "signedData":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.SignedData: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.SignedData: %w", err)
					}
					if len(bval) > 0 {
						t.SignedData = []uint8(bval)
					}
				}

				// t.Signer ([]uint8) (slice)
			case "signer":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Signer: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Signer: %w", err)
					}
					if len(bval) > 0 {
						t.Signer = []uint8(bval)
					}
				}

				// t.V (uint8) (uint8)
			case "v":
				{
					nval, err := jr.ReadNumberAsUint8()
					if err != nil {
						return fmt.Errorf("reading uint8 for field t.V: %w", err)
					}
					t.V = uint8(nval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AuthSignatureModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AuthSignatureModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AuthSignatureModel")
			}
		}
	}

	return nil
}
func (t *MetadataModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Keys ([]string) (slice)
	if len("keys") > 8192 {
		return fmt.Errorf("string in field \"keys\" was too long")
	}
	if err := jw.WriteString(string("keys")); err != nil {
		return fmt.Errorf("writing string for field \"keys\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Keys) > 8192 {
		return fmt.Errorf("slice value in field t.Keys was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Keys: %w", err)
	}
	for i, v := range t.Keys {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Keys: %w", err)
			}
		}
		if len(v) > 8192 {
			return fmt.Errorf("string in field v was too long")
		}
		if err := jw.WriteString(string(v)); err != nil {
			return fmt.Errorf("writing string for field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Keys: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Values (map[string]string) (map)
	if len("values") > 8192 {
		return fmt.Errorf("string in field \"values\" was too long")
	}
	if err := jw.WriteString(string("values")); err != nil {
		return fmt.Errorf("writing string for field \"values\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Values) > 4096 {
			return fmt.Errorf("cannot marshal t.Values map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Values: %w", err)
		}

		keys := make([]string, 0, len(t.Values))
		for k := range t.Values {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Values: %w", err)
				}
			}
			v := t.Values[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Values: %w", err)
			}

			if len(v) > 8192 {
				return fmt.Errorf("string in field v was too long")
			}
			if err := jw.WriteString(string(v)); err != nil {
				return fmt.Errorf("writing string for field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Values: %w", err)
		}
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *MetadataModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = MetadataModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for MetadataModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for MetadataModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for MetadataModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field MetadataModel: string too large")
				}
				return fmt.Errorf("reading string for field MetadataModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field MetadataModel: %w", err)
			}
			switch name {

			// t.Keys ([]string) (slice)
			case "keys":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Keys: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Keys: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Keys: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]string, 1)
							{
								sval, err := jr.ReadString(8192)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading string for field item[0]: string too long")
									}
									return fmt.Errorf("reading string for field item[0]: %w", err)
								}
								item[0] = string(sval)
							}
							t.Keys = append(t.Keys, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Keys: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Keys: slice too large")
							}
						}
					}

				}

				// t.Values (map[string]string) (map)
			case "values":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Values: %w", err)
				}

				t.Values = map[string]string{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Values: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Values: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Values: %w", err)
						}
						var v string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field v: string too long")
								}
								return fmt.Errorf("reading string for field v: %w", err)
							}
							v = string(sval)
						}
						t.Values[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Values: %w", err)
						}
						if close {
							break
						}
					}
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for MetadataModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field MetadataModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for MetadataModel")
			}
		}
	}

	return nil
}
func (t *PieceProofsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Proofs ([]cid.Cid) (slice)
	if len("proofs") > 8192 {
		return fmt.Errorf("string in field \"proofs\" was too long")
	}
	if err := jw.WriteString(string("proofs")); err != nil {
		return fmt.Errorf("writing string for field \"proofs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Proofs) > 8192 {
		return fmt.Errorf("slice value in field t.Proofs was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Proofs: %w", err)
	}
	for i, v := range t.Proofs {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Proofs: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("writing CID for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Proofs: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *PieceProofsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = PieceProofsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for PieceProofsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for PieceProofsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for PieceProofsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field PieceProofsModel: string too large")
				}
				return fmt.Errorf("reading string for field PieceProofsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field PieceProofsModel: %w", err)
			}
			switch name {

			// t.Proofs ([]cid.Cid) (slice)
			case "proofs":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Proofs: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Proofs: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Proofs: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("reading CID for field item[0]: %w", err)
								}
								item[0] = c

							}
							t.Proofs = append(t.Proofs, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Proofs: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Proofs: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for PieceProofsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field PieceProofsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for PieceProofsModel")
			}
		}
	}

	return nil
}
func (t *DataSetCreateArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return fmt.Errorf("string in field \"dataSet\" was too long")
	}
	if err := jw.WriteString(string("dataSet")); err != nil {
		return fmt.Errorf("writing string for field \"dataSet\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.DataSet) > 2097152 {
		return fmt.Errorf("byte array in field t.DataSet was too long")
	}

	if err := jw.WriteBytes(t.DataSet); err != nil {
		return fmt.Errorf("writing bytes for field t.DataSet: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Metadata (datamodel.MetadataModel) (struct)
	if len("metadata") > 8192 {
		return fmt.Errorf("string in field \"metadata\" was too long")
	}
	if err := jw.WriteString(string("metadata")); err != nil {
		return fmt.Errorf("writing string for field \"metadata\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Metadata.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Metadata: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Payee ([]uint8) (slice)
	if len("payee") > 8192 {
		return fmt.Errorf("string in field \"payee\" was too long")
	}
	if err := jw.WriteString(string("payee")); err != nil {
		return fmt.Errorf("writing string for field \"payee\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Payee) > 2097152 {
		return fmt.Errorf("byte array in field t.Payee was too long")
	}

	if err := jw.WriteBytes(t.Payee); err != nil {
		return fmt.Errorf("writing bytes for field t.Payee: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *DataSetCreateArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = DataSetCreateArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for DataSetCreateArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for DataSetCreateArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for DataSetCreateArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field DataSetCreateArgumentsModel: string too large")
				}
				return fmt.Errorf("reading string for field DataSetCreateArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field DataSetCreateArgumentsModel: %w", err)
			}
			switch name {

			// t.DataSet ([]uint8) (slice)
			case "dataSet":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.DataSet: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.DataSet: %w", err)
					}
					if len(bval) > 0 {
						t.DataSet = []uint8(bval)
					}
				}

				// t.Metadata (datamodel.MetadataModel) (struct)
			case "metadata":

				if err := t.Metadata.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Metadata: %w", err)
				}

				// t.Payee ([]uint8) (slice)
			case "payee":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Payee: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Payee: %w", err)
					}
					if len(bval) > 0 {
						t.Payee = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for DataSetCreateArgumentsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field DataSetCreateArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for DataSetCreateArgumentsModel")
			}
		}
	}

	return nil
}
func (t *DataSetDeleteArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return fmt.Errorf("string in field \"dataSet\" was too long")
	}
	if err := jw.WriteString(string("dataSet")); err != nil {
		return fmt.Errorf("writing string for field \"dataSet\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.DataSet) > 2097152 {
		return fmt.Errorf("byte array in field t.DataSet was too long")
	}

	if err := jw.WriteBytes(t.DataSet); err != nil {
		return fmt.Errorf("writing bytes for field t.DataSet: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *DataSetDeleteArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = DataSetDeleteArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for DataSetDeleteArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for DataSetDeleteArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for DataSetDeleteArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field DataSetDeleteArgumentsModel: string too large")
				}
				return fmt.Errorf("reading string for field DataSetDeleteArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field DataSetDeleteArgumentsModel: %w", err)
			}
			switch name {

			// t.DataSet ([]uint8) (slice)
			case "dataSet":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.DataSet: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.DataSet: %w", err)
					}
					if len(bval) > 0 {
						t.DataSet = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for DataSetDeleteArgumentsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field DataSetDeleteArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for DataSetDeleteArgumentsModel")
			}
		}
	}

	return nil
}
func (t *PiecesAddArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return fmt.Errorf("string in field \"dataSet\" was too long")
	}
	if err := jw.WriteString(string("dataSet")); err != nil {
		return fmt.Errorf("writing string for field \"dataSet\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.DataSet) > 2097152 {
		return fmt.Errorf("byte array in field t.DataSet was too long")
	}

	if err := jw.WriteBytes(t.DataSet); err != nil {
		return fmt.Errorf("writing bytes for field t.DataSet: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Metadata ([]datamodel.MetadataModel) (slice)
	if len("metadata") > 8192 {
		return fmt.Errorf("string in field \"metadata\" was too long")
	}
	if err := jw.WriteString(string("metadata")); err != nil {
		return fmt.Errorf("writing string for field \"metadata\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Metadata) > 8192 {
		return fmt.Errorf("slice value in field t.Metadata was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Metadata: %w", err)
	}
	for i, v := range t.Metadata {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Metadata: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Metadata: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Nonce ([]uint8) (slice)
	if len("nonce") > 8192 {
		return fmt.Errorf("string in field \"nonce\" was too long")
	}
	if err := jw.WriteString(string("nonce")); err != nil {
		return fmt.Errorf("writing string for field \"nonce\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Nonce) > 2097152 {
		return fmt.Errorf("byte array in field t.Nonce was too long")
	}

	if err := jw.WriteBytes(t.Nonce); err != nil {
		return fmt.Errorf("writing bytes for field t.Nonce: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.PieceData ([][]uint8) (slice)
	if len("pieceData") > 8192 {
		return fmt.Errorf("string in field \"pieceData\" was too long")
	}
	if err := jw.WriteString(string("pieceData")); err != nil {
		return fmt.Errorf("writing string for field \"pieceData\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.PieceData) > 8192 {
		return fmt.Errorf("slice value in field t.PieceData was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.PieceData: %w", err)
	}
	for i, v := range t.PieceData {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.PieceData: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("writing bytes for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.PieceData: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Proofs ([]datamodel.PieceProofsModel) (slice)
	if len("proofs") > 8192 {
		return fmt.Errorf("string in field \"proofs\" was too long")
	}
	if err := jw.WriteString(string("proofs")); err != nil {
		return fmt.Errorf("writing string for field \"proofs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Proofs) > 8192 {
		return fmt.Errorf("slice value in field t.Proofs was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Proofs: %w", err)
	}
	for i, v := range t.Proofs {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Proofs: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Proofs: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *PiecesAddArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = PiecesAddArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for PiecesAddArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for PiecesAddArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for PiecesAddArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field PiecesAddArgumentsModel: string too large")
				}
				return fmt.Errorf("reading string for field PiecesAddArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field PiecesAddArgumentsModel: %w", err)
			}
			switch name {

			// t.DataSet ([]uint8) (slice)
			case "dataSet":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.DataSet: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.DataSet: %w", err)
					}
					if len(bval) > 0 {
						t.DataSet = []uint8(bval)
					}
				}

				// t.Metadata ([]datamodel.MetadataModel) (slice)
			case "metadata":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Metadata: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Metadata: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Metadata: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]MetadataModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Metadata = append(t.Metadata, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Metadata: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Metadata: slice too large")
							}
						}
					}

				}

				// t.Nonce ([]uint8) (slice)
			case "nonce":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Nonce: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Nonce: %w", err)
					}
					if len(bval) > 0 {
						t.Nonce = []uint8(bval)
					}
				}

				// t.PieceData ([][]uint8) (slice)
			case "pieceData":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.PieceData: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.PieceData: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.PieceData: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading bytes for field item[0]: byte array too large")
									}
									return fmt.Errorf("reading bytes for field item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.PieceData = append(t.PieceData, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.PieceData: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.PieceData: slice too large")
							}
						}
					}

				}

				// t.Proofs ([]datamodel.PieceProofsModel) (slice)
			case "proofs":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Proofs: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Proofs: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Proofs: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]PieceProofsModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Proofs = append(t.Proofs, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Proofs: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Proofs: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for PiecesAddArgumentsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field PiecesAddArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for PiecesAddArgumentsModel")
			}
		}
	}

	return nil
}
func (t *PiecesRemoveScheduleArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.DataSet ([]uint8) (slice)
	if len("dataSet") > 8192 {
		return fmt.Errorf("string in field \"dataSet\" was too long")
	}
	if err := jw.WriteString(string("dataSet")); err != nil {
		return fmt.Errorf("writing string for field \"dataSet\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.DataSet) > 2097152 {
		return fmt.Errorf("byte array in field t.DataSet was too long")
	}

	if err := jw.WriteBytes(t.DataSet); err != nil {
		return fmt.Errorf("writing bytes for field t.DataSet: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Pieces ([][]uint8) (slice)
	if len("pieces") > 8192 {
		return fmt.Errorf("string in field \"pieces\" was too long")
	}
	if err := jw.WriteString(string("pieces")); err != nil {
		return fmt.Errorf("writing string for field \"pieces\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Pieces) > 8192 {
		return fmt.Errorf("slice value in field t.Pieces was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Pieces: %w", err)
	}
	for i, v := range t.Pieces {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Pieces: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("writing bytes for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Pieces: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *PiecesRemoveScheduleArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = PiecesRemoveScheduleArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for PiecesRemoveScheduleArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for PiecesRemoveScheduleArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for PiecesRemoveScheduleArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field PiecesRemoveScheduleArgumentsModel: string too large")
				}
				return fmt.Errorf("reading string for field PiecesRemoveScheduleArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field PiecesRemoveScheduleArgumentsModel: %w", err)
			}
			switch name {

			// t.DataSet ([]uint8) (slice)
			case "dataSet":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.DataSet: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.DataSet: %w", err)
					}
					if len(bval) > 0 {
						t.DataSet = []uint8(bval)
					}
				}

				// t.Pieces ([][]uint8) (slice)
			case "pieces":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Pieces: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Pieces: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Pieces: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading bytes for field item[0]: byte array too large")
									}
									return fmt.Errorf("reading bytes for field item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Pieces = append(t.Pieces, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Pieces: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Pieces: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for PiecesRemoveScheduleArgumentsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field PiecesRemoveScheduleArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for PiecesRemoveScheduleArgumentsModel")
			}
		}
	}

	return nil
}
