// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *BlobModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("string in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("writing string for field \"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("writing bytes for field t.Digest: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *BlobModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BlobModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for BlobModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for BlobModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for BlobModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field BlobModel: string too large")
				}
				return fmt.Errorf("reading string for field BlobModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field BlobModel: %w", err)
			}
			switch name {

			// t.Digest (multihash.Multihash) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Digest: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for BlobModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field BlobModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for BlobModel")
			}
		}
	}

	return nil
}
func (t *RetrieveArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Blob (datamodel.BlobModel) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Range (datamodel.RangeModel) (struct)
	if len("range") > 8192 {
		return fmt.Errorf("string in field \"range\" was too long")
	}
	if err := jw.WriteString(string("range")); err != nil {
		return fmt.Errorf("writing string for field \"range\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Range.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Range: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RetrieveArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RetrieveArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RetrieveArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RetrieveArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RetrieveArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RetrieveArgumentsModel: string too large")
				}
				return fmt.Errorf("reading string for field RetrieveArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RetrieveArgumentsModel: %w", err)
			}
			switch name {

			// t.Blob (datamodel.BlobModel) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.Range (datamodel.RangeModel) (struct)
			case "range":

				if err := t.Range.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Range: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RetrieveArgumentsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RetrieveArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RetrieveArgumentsModel")
			}
		}
	}

	return nil
}
