// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *RangeModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field RangeModel: %w", err)
	}

	// t.Start (int64) (int64)

	if err := jw.WriteInt64(int64(t.Start)); err != nil {
		return fmt.Errorf("writing int64 for field t.Start: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field End: %w", err)
	}

	// t.End (int64) (int64)

	if err := jw.WriteInt64(int64(t.End)); err != nil {
		return fmt.Errorf("writing int64 for field t.End: %w", err)
	}

	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field RangeModel: %w", err)
	}
	return nil
}

func (t *RangeModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RangeModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field RangeModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field RangeModel: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field RangeModel: %w", err)
		}
	} else {

		// t.Start (int64) (int64)

		{

			nval, err := jr.ReadNumberAsInt64()
			if err != nil {
				return fmt.Errorf("reading int64 for field t.Start: %w", err)
			}
			t.Start = int64(nval)

		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field RangeModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.End (int64) (int64)

		{

			nval, err := jr.ReadNumberAsInt64()
			if err != nil {
				return fmt.Errorf("reading int64 for field t.End: %w", err)
			}
			t.End = int64(nval)

		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field RangeModel: %w", err)
		}
	}
	return nil
}
