//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package principal

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *InvalidateArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := false

	// t.Principal (string) (string)
	if len("principal") > 8192 {
		return fmt.Errorf("string in field \"principal\" was too long")
	}
	if err := jw.WriteString(string("principal")); err != nil {
		return fmt.Errorf("writing string for field \"principal\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Principal) > 8192 {
		return fmt.Errorf("string in field t.Principal was too long")
	}
	if err := jw.WriteString(string(t.Principal)); err != nil {
		return fmt.Errorf("writing string for field t.Principal: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Tenant (did.DID) (struct)
	if len("tenant") > 8192 {
		return fmt.Errorf("string in field \"tenant\" was too long")
	}
	if err := jw.WriteString(string("tenant")); err != nil {
		return fmt.Errorf("writing string for field \"tenant\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Tenant.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Tenant: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *InvalidateArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = InvalidateArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for InvalidateArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for InvalidateArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for InvalidateArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field InvalidateArguments: string too large")
				}
				return fmt.Errorf("reading string for field InvalidateArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field InvalidateArguments: %w", err)
			}
			switch name {

			// t.Principal (string) (string)
			case "principal":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Principal: string too long")
						}
						return fmt.Errorf("reading string for field t.Principal: %w", err)
					}
					t.Principal = string(sval)
				}

				// t.Tenant (did.DID) (struct)
			case "tenant":

				if err := t.Tenant.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Tenant: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for InvalidateArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field InvalidateArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for InvalidateArguments")
			}
		}
	}

	return nil
}
