//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package provider

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *AddArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Consumer (did.DID) (struct)
	if len("consumer") > 8192 {
		return fmt.Errorf("string in field \"consumer\" was too long")
	}
	if err := jw.WriteString(string("consumer")); err != nil {
		return fmt.Errorf("writing string for field \"consumer\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Consumer.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Consumer: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("string in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("writing string for field \"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Provider: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AddArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AddArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AddArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AddArguments: string too large")
				}
				return fmt.Errorf("reading string for field AddArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AddArguments: %w", err)
			}
			switch name {

			// t.Consumer (did.DID) (struct)
			case "consumer":

				if err := t.Consumer.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Consumer: %w", err)
				}

				// t.Provider (did.DID) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AddArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AddArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AddArguments")
			}
		}
	}

	return nil
}
func (t *AddOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.ID (string) (string)
	if len("id") > 8192 {
		return fmt.Errorf("string in field \"id\" was too long")
	}
	if err := jw.WriteString(string("id")); err != nil {
		return fmt.Errorf("writing string for field \"id\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.ID) > 8192 {
		return fmt.Errorf("string in field t.ID was too long")
	}
	if err := jw.WriteString(string(t.ID)); err != nil {
		return fmt.Errorf("writing string for field t.ID: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AddOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AddOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AddOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AddOK: string too large")
				}
				return fmt.Errorf("reading string for field AddOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AddOK: %w", err)
			}
			switch name {

			// t.ID (string) (string)
			case "id":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.ID: string too long")
						}
						return fmt.Errorf("reading string for field t.ID: %w", err)
					}
					t.ID = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AddOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AddOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AddOK")
			}
		}
	}

	return nil
}
