//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package metrics

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *SampleItem) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field SampleItem: %w", err)
	}

	// t.Timestamp (int64) (int64)

	if err := jw.WriteInt64(int64(t.Timestamp)); err != nil {
		return fmt.Errorf("writing int64 for field t.Timestamp: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field BytesStored: %w", err)
	}

	// t.BytesStored (uint64) (uint64)

	if err := jw.WriteUint64(uint64(t.BytesStored)); err != nil {
		return fmt.Errorf("writing uint64 for field t.BytesStored: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field BytesIngested: %w", err)
	}

	// t.BytesIngested (uint64) (uint64)

	if err := jw.WriteUint64(uint64(t.BytesIngested)); err != nil {
		return fmt.Errorf("writing uint64 for field t.BytesIngested: %w", err)
	}

	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field SampleItem: %w", err)
	}
	return nil
}

func (t *SampleItem) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SampleItem{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field SampleItem: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field SampleItem: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field SampleItem: %w", err)
		}
	} else {

		// t.Timestamp (int64) (int64)

		{

			nval, err := jr.ReadNumberAsInt64()
			if err != nil {
				return fmt.Errorf("reading int64 for field t.Timestamp: %w", err)
			}
			t.Timestamp = int64(nval)

		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field SampleItem: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 3")
			}
		}

		// t.BytesStored (uint64) (uint64)

		{

			nval, err := jr.ReadNumberAsUint64()
			if err != nil {
				return fmt.Errorf("reading uint64 for field t.BytesStored: %w", err)
			}
			t.BytesStored = uint64(nval)

		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field SampleItem: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 2 < 3")
			}
		}

		// t.BytesIngested (uint64) (uint64)

		{

			nval, err := jr.ReadNumberAsUint64()
			if err != nil {
				return fmt.Errorf("reading uint64 for field t.BytesIngested: %w", err)
			}
			t.BytesIngested = uint64(nval)

		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field SampleItem: %w", err)
		}
	}
	return nil
}
