// Package metrics defines the usage metering capabilities. The space the
// samples describe is the invocation subject, so it never appears in the
// arguments.
//
// SampleSet is a DID-keyed map. cbor-gen / dag-json-gen only generate
// string-keyed maps, so it has a hand-written codec (see codec.go) and is
// defined as a struct wrapping the map so that structs embedding it can still
// be generated as usual.
package metrics

import "github.com/fil-forge/ucantone/did"

// SampleArguments is the argument shape of `/metrics/sample`. It asks for a
// usage time series for the invocation subject, covering [From, To) in buckets
// of Window seconds.
//
// All three fields are required and are expressed in seconds: From and To are
// Unix timestamps, From inclusive and To exclusive, and Window is a duration.
// Window need not divide the range evenly, and To may lie in the future; the
// service shortens the range to end at the present and SampleOK reports the
// range actually covered.
//
// The series the service returns is dense: a bucket in which nothing happened
// still yields a sample. Consumers take an unweighted mean over the stored-bytes
// series, so a bucket dropped for want of activity would reweight that mean.
type SampleArguments struct {
	// From is the start of the range, inclusive, as a Unix timestamp in seconds.
	From int64 `cborgen:"from" dagjsongen:"from"`
	// To is the end of the range, exclusive, as a Unix timestamp in seconds.
	To int64 `cborgen:"to" dagjsongen:"to"`
	// Window is the width of one bucket, in seconds. It must be positive.
	Window int64 `cborgen:"window" dagjsongen:"window"`
}

// SampleOK is the success return for `/metrics/sample`. Each series in Samples
// holds exactly one entry per bucket in [From, To), ordered by ascending
// Timestamp, with no gaps.
//
// From, To and Window restate the range the samples cover. From and Window
// always equal the request's. To is the requested To clamped to the service's
// current time, and never earlier than From: the service reports what has
// already happened rather than padding out buckets that lie ahead. A request
// whose range is entirely in the future therefore returns To equal to From and
// no samples.
//
// The last bucket is short whenever Window does not divide To-From, which
// includes the ordinary case of a range running up to the present. A short
// bucket is still a bucket: it carries one sample, timestamped at To. Its
// BytesStored is exact, being a reading taken at that instant, while its
// BytesIngested covers only the part of the window that has elapsed and so
// reads low against a full one.
type SampleOK struct {
	// From is the start of the range covered, inclusive, as a Unix timestamp in
	// seconds.
	From int64 `cborgen:"from" dagjsongen:"from"`
	// To is the end of the range covered, exclusive, as a Unix timestamp in
	// seconds. It is the requested To clamped to the service's current time.
	To int64 `cborgen:"to" dagjsongen:"to"`
	// Window is the width of one bucket, in seconds.
	Window int64 `cborgen:"window" dagjsongen:"window"`
	// Samples is the series recorded against each of the space's storage
	// providers.
	Samples SampleSet `cborgen:"samples" dagjsongen:"samples"`
}

// SampleSet maps a storage provider DID to the series recorded against it.
// Every series shares one bucket grid: the same count, the same timestamps,
// covering [From, To).
//
// Usage is recorded per provider, so a space provisioned with several holds
// several series. They describe the same stored bytes from each provider's
// side rather than parts of a whole, so a consumer picks the provider it cares
// about; adding them together would count the same bytes once per provider.
//
// It is a struct wrapping the map (rather than a named map type) so that
// structs embedding it can be generated by cbor-gen / dag-json-gen, which
// delegate to a struct field's MarshalCBOR but cannot generate a DID-keyed map
// inline. On the wire it encodes as the bare map, not as an object with an
// "entries" key.
type SampleSet struct {
	Entries map[did.DID][]SampleItem
}

// SampleItem is one bucket of the series.
//
// It is tuple encoded, as [Timestamp, BytesStored, BytesIngested], because it
// repeats once per bucket and a map would carry its three key names along with
// it — a 32 day hourly series is about a third the size this way. The order of
// the fields is therefore part of the wire format: a field may be appended,
// but none may be reordered or removed.
//
// Timestamp is the end of the bucket rather than its start. Consumers key a
// sample to the instant its window closes, and a start-of-window timestamp
// lands the value in the neighbouring bucket when several series are collapsed
// onto one grid.
//
// BytesStored is a gauge: the bytes the space holds as of Timestamp, counting
// everything stored and not yet removed before that instant. BytesIngested is a
// flow: the bytes added during the bucket. Removals do not reduce BytesIngested;
// they show up in the next BytesStored.
//
// There is no egress here. Egress is accounted for by the egress tracking
// service, which sees retrieval receipts this service never handles.
type SampleItem struct {
	// Timestamp is the end of the bucket, as a Unix timestamp in seconds.
	Timestamp int64 `cborgen:"timestamp" dagjsongen:"timestamp"`
	// BytesStored is the bytes the space holds at Timestamp.
	BytesStored uint64 `cborgen:"bytesStored" dagjsongen:"bytesStored"`
	// BytesIngested is the bytes added to the space during the bucket.
	BytesIngested uint64 `cborgen:"bytesIngested" dagjsongen:"bytesIngested"`
}
