//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package content

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *Range) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field Range: %w", err)
	}

	// t.Start (uint64) (uint64)

	if err := jw.WriteUint64(uint64(t.Start)); err != nil {
		return fmt.Errorf("writing uint64 for field t.Start: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field End: %w", err)
	}

	// t.End (uint64) (uint64)

	if err := jw.WriteUint64(uint64(t.End)); err != nil {
		return fmt.Errorf("writing uint64 for field t.End: %w", err)
	}

	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field Range: %w", err)
	}
	return nil
}

func (t *Range) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Range{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field Range: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field Range: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field Range: %w", err)
		}
	} else {

		// t.Start (uint64) (uint64)

		{

			nval, err := jr.ReadNumberAsUint64()
			if err != nil {
				return fmt.Errorf("reading uint64 for field t.Start: %w", err)
			}
			t.Start = uint64(nval)

		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field Range: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.End (uint64) (uint64)

		{

			nval, err := jr.ReadNumberAsUint64()
			if err != nil {
				return fmt.Errorf("reading uint64 for field t.End: %w", err)
			}
			t.End = uint64(nval)

		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field Range: %w", err)
		}
	}
	return nil
}
