//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package s3

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *Request) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Headers (map[string]string) (map)
	if len("headers") > 8192 {
		return fmt.Errorf("string in field \"headers\" was too long")
	}
	if err := jw.WriteString(string("headers")); err != nil {
		return fmt.Errorf("writing string for field \"headers\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Headers) > 4096 {
			return fmt.Errorf("cannot marshal t.Headers map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Headers: %w", err)
		}

		keys := make([]string, 0, len(t.Headers))
		for k := range t.Headers {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Headers: %w", err)
				}
			}
			v := t.Headers[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Headers: %w", err)
			}

			if len(v) > 8192 {
				return fmt.Errorf("string in field v was too long")
			}
			if err := jw.WriteString(string(v)); err != nil {
				return fmt.Errorf("writing string for field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Headers: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Method (string) (string)
	if len("method") > 8192 {
		return fmt.Errorf("string in field \"method\" was too long")
	}
	if err := jw.WriteString(string("method")); err != nil {
		return fmt.Errorf("writing string for field \"method\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Method) > 8192 {
		return fmt.Errorf("string in field t.Method was too long")
	}
	if err := jw.WriteString(string(t.Method)); err != nil {
		return fmt.Errorf("writing string for field t.Method: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.URL (string) (string)
	if len("url") > 8192 {
		return fmt.Errorf("string in field \"url\" was too long")
	}
	if err := jw.WriteString(string("url")); err != nil {
		return fmt.Errorf("writing string for field \"url\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.URL) > 8192 {
		return fmt.Errorf("string in field t.URL was too long")
	}
	if err := jw.WriteString(string(t.URL)); err != nil {
		return fmt.Errorf("writing string for field t.URL: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Request) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Request{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Request: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Request: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Request: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Request: string too large")
				}
				return fmt.Errorf("reading string for field Request: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Request: %w", err)
			}
			switch name {

			// t.Headers (map[string]string) (map)
			case "headers":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Headers: %w", err)
				}

				t.Headers = map[string]string{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Headers: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Headers: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Headers: %w", err)
						}
						var v string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field v: string too long")
								}
								return fmt.Errorf("reading string for field v: %w", err)
							}
							v = string(sval)
						}
						t.Headers[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Headers: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.Method (string) (string)
			case "method":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Method: string too long")
						}
						return fmt.Errorf("reading string for field t.Method: %w", err)
					}
					t.Method = string(sval)
				}

				// t.URL (string) (string)
			case "url":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.URL: string too long")
						}
						return fmt.Errorf("reading string for field t.URL: %w", err)
					}
					t.URL = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Request: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Request: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Request")
			}
		}
	}

	return nil
}
func (t *VerificationKey) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Data ([]uint8) (slice)
	if len("data") > 8192 {
		return fmt.Errorf("string in field \"data\" was too long")
	}
	if err := jw.WriteString(string("data")); err != nil {
		return fmt.Errorf("writing string for field \"data\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Data) > 2097152 {
		return fmt.Errorf("byte array in field t.Data was too long")
	}

	if err := jw.WriteBytes(t.Data); err != nil {
		return fmt.Errorf("writing bytes for field t.Data: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Kind (string) (string)
	if len("kind") > 8192 {
		return fmt.Errorf("string in field \"kind\" was too long")
	}
	if err := jw.WriteString(string("kind")); err != nil {
		return fmt.Errorf("writing string for field \"kind\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Kind) > 8192 {
		return fmt.Errorf("string in field t.Kind was too long")
	}
	if err := jw.WriteString(string(t.Kind)); err != nil {
		return fmt.Errorf("writing string for field t.Kind: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *VerificationKey) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = VerificationKey{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for VerificationKey: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for VerificationKey: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for VerificationKey: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field VerificationKey: string too large")
				}
				return fmt.Errorf("reading string for field VerificationKey: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field VerificationKey: %w", err)
			}
			switch name {

			// t.Data ([]uint8) (slice)
			case "data":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Data: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Data: %w", err)
					}
					if len(bval) > 0 {
						t.Data = []uint8(bval)
					}
				}

				// t.Kind (string) (string)
			case "kind":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Kind: string too long")
						}
						return fmt.Errorf("reading string for field t.Kind: %w", err)
					}
					t.Kind = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for VerificationKey: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field VerificationKey: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for VerificationKey")
			}
		}
	}

	return nil
}
