// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *RangeModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field RangeModel: %w", err)
	}

	// t.Start (int64) (int64)

	if err := jw.WriteInt64(int64(t.Start)); err != nil {
		return fmt.Errorf("writing int64 for field t.Start: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field End: %w", err)
	}

	// t.End (int64) (int64)

	if err := jw.WriteInt64(int64(t.End)); err != nil {
		return fmt.Errorf("writing int64 for field t.End: %w", err)
	}

	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field RangeModel: %w", err)
	}
	return nil
}

func (t *RangeModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RangeModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field RangeModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field RangeModel: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field RangeModel: %w", err)
		}
	} else {

		// t.Start (int64) (int64)

		{

			nval, err := jr.ReadNumberAsInt64()
			if err != nil {
				return fmt.Errorf("reading int64 for field t.Start: %w", err)
			}
			t.Start = int64(nval)

		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field RangeModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.End (int64) (int64)

		{

			nval, err := jr.ReadNumberAsInt64()
			if err != nil {
				return fmt.Errorf("reading int64 for field t.End: %w", err)
			}
			t.End = int64(nval)

		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field RangeModel: %w", err)
		}
	}
	return nil
}

func (t *BlobSliceModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field BlobSliceModel: %w", err)
	}

	// t.Digest (multihash.Multihash) (slice)
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("writing bytes for field t.Digest: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Range: %w", err)
	}

	// t.Range (datamodel.RangeModel) (struct)
	if err := t.Range.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Range: %w", err)
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field BlobSliceModel: %w", err)
	}
	return nil
}

func (t *BlobSliceModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BlobSliceModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field BlobSliceModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field BlobSliceModel: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field BlobSliceModel: %w", err)
		}
	} else {

		// t.Digest (multihash.Multihash) (slice)

		{
			bval, err := jr.ReadBytes(2097152)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading bytes for field t.Digest: byte array too large")
				}
				return fmt.Errorf("reading bytes for field t.Digest: %w", err)
			}
			if len(bval) > 0 {
				t.Digest = []uint8(bval)
			}
		}

		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field BlobSliceModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.Range (datamodel.RangeModel) (struct)

		if err := t.Range.UnmarshalDagJSON(jr); err != nil {
			return fmt.Errorf("unmarshaling t.Range: %w", err)
		}

		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field BlobSliceModel: %w", err)
		}
	}
	return nil
}

func (t *BlobIndexModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field BlobIndexModel: %w", err)
	}

	// t.Digest (multihash.Multihash) (slice)
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("writing bytes for field t.Digest: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Slices: %w", err)
	}

	// t.Slices ([]datamodel.BlobSliceModel) (slice)
	if len(t.Slices) > 8192 {
		return fmt.Errorf("slice value in field t.Slices was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Slices: %w", err)
	}
	for i, v := range t.Slices {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Slices: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Slices: %w", err)
	}

	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field BlobIndexModel: %w", err)
	}
	return nil
}

func (t *BlobIndexModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BlobIndexModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field BlobIndexModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field BlobIndexModel: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field BlobIndexModel: %w", err)
		}
	} else {

		// t.Digest (multihash.Multihash) (slice)

		{
			bval, err := jr.ReadBytes(2097152)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading bytes for field t.Digest: byte array too large")
				}
				return fmt.Errorf("reading bytes for field t.Digest: %w", err)
			}
			if len(bval) > 0 {
				t.Digest = []uint8(bval)
			}
		}

		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field BlobIndexModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.Slices ([]datamodel.BlobSliceModel) (slice)

		{

			if err := jr.ReadArrayOpen(); err != nil {
				return fmt.Errorf("reading array open for field t.Slices: %w", err)
			}

			close, err := jr.PeekArrayClose()
			if err != nil {
				return fmt.Errorf("peeking array close for field t.Slices: %w", err)
			}
			if close {
				if err := jr.ReadArrayClose(); err != nil {
					return fmt.Errorf("reading array close for field t.Slices: %w", err)
				}

			} else {
				for i := 0; i < 8192; i++ {
					item := make([]BlobSliceModel, 1)

					if err := item[0].UnmarshalDagJSON(jr); err != nil {
						return fmt.Errorf("unmarshaling item[0]: %w", err)
					}

					t.Slices = append(t.Slices, item[0])

					close, err := jr.ReadArrayCloseOrComma()
					if err != nil {
						return fmt.Errorf("reading array close or comma for field t.Slices: %w", err)
					}
					if close {
						break
					}
					if i == 8192-1 {
						return fmt.Errorf("reading array for field t.Slices: slice too large")
					}
				}
			}

		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field BlobIndexModel: %w", err)
		}
	}
	return nil
}
