//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package access

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	command "github.com/fil-forge/ucantone/ucan/command"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *RequestArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Attenuations ([]access.CapabilityRequest) (slice)
	if len("att") > 8192 {
		return fmt.Errorf("string in field \"att\" was too long")
	}
	if err := jw.WriteString(string("att")); err != nil {
		return fmt.Errorf("writing string for field \"att\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Attenuations) > 8192 {
		return fmt.Errorf("slice value in field t.Attenuations was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Attenuations: %w", err)
	}
	for i, v := range t.Attenuations {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Attenuations: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Attenuations: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Issuer (did.DID) (struct)
	if len("iss") > 8192 {
		return fmt.Errorf("string in field \"iss\" was too long")
	}
	if err := jw.WriteString(string("iss")); err != nil {
		return fmt.Errorf("writing string for field \"iss\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Issuer.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Issuer: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RequestArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RequestArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RequestArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RequestArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RequestArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RequestArguments: string too large")
				}
				return fmt.Errorf("reading string for field RequestArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RequestArguments: %w", err)
			}
			switch name {

			// t.Attenuations ([]access.CapabilityRequest) (slice)
			case "att":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Attenuations: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Attenuations: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Attenuations: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]CapabilityRequest, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Attenuations = append(t.Attenuations, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Attenuations: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Attenuations: slice too large")
							}
						}
					}

				}

				// t.Issuer (did.DID) (struct)
			case "iss":

				if err := t.Issuer.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Issuer: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RequestArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RequestArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RequestArguments")
			}
		}
	}

	return nil
}
func (t *CapabilityRequest) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Command (command.Command) (string)
	if len("cmd") > 8192 {
		return fmt.Errorf("string in field \"cmd\" was too long")
	}
	if err := jw.WriteString(string("cmd")); err != nil {
		return fmt.Errorf("writing string for field \"cmd\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Command) > 8192 {
		return fmt.Errorf("string in field t.Command was too long")
	}
	if err := jw.WriteString(string(t.Command)); err != nil {
		return fmt.Errorf("writing string for field t.Command: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *CapabilityRequest) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = CapabilityRequest{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for CapabilityRequest: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for CapabilityRequest: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for CapabilityRequest: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field CapabilityRequest: string too large")
				}
				return fmt.Errorf("reading string for field CapabilityRequest: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field CapabilityRequest: %w", err)
			}
			switch name {

			// t.Command (command.Command) (string)
			case "cmd":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Command: string too long")
						}
						return fmt.Errorf("reading string for field t.Command: %w", err)
					}
					t.Command = command.Command(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for CapabilityRequest: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field CapabilityRequest: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for CapabilityRequest")
			}
		}
	}

	return nil
}
func (t *RequestOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Confirm (promise.AwaitOK) (struct)
	if len("confirm") > 8192 {
		return fmt.Errorf("string in field \"confirm\" was too long")
	}
	if err := jw.WriteString(string("confirm")); err != nil {
		return fmt.Errorf("writing string for field \"confirm\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Confirm.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Confirm: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Expiration (int64) (int64)
	if len("exp") > 8192 {
		return fmt.Errorf("string in field \"exp\" was too long")
	}
	if err := jw.WriteString(string("exp")); err != nil {
		return fmt.Errorf("writing string for field \"exp\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Expiration)); err != nil {
		return fmt.Errorf("writing int64 for field t.Expiration: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Request (cid.Cid) (struct)
	if len("req") > 8192 {
		return fmt.Errorf("string in field \"req\" was too long")
	}
	if err := jw.WriteString(string("req")); err != nil {
		return fmt.Errorf("writing string for field \"req\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Request); err != nil {
		return fmt.Errorf("writing CID for field t.Request: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RequestOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RequestOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RequestOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RequestOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RequestOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RequestOK: string too large")
				}
				return fmt.Errorf("reading string for field RequestOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RequestOK: %w", err)
			}
			switch name {

			// t.Confirm (promise.AwaitOK) (struct)
			case "confirm":

				if err := t.Confirm.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Confirm: %w", err)
				}

				// t.Expiration (int64) (int64)
			case "exp":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Expiration: %w", err)
					}
					t.Expiration = int64(nval)

				}

				// t.Request (cid.Cid) (struct)
			case "req":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Request: %w", err)
					}
					t.Request = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RequestOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RequestOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RequestOK")
			}
		}
	}

	return nil
}
func (t *ClaimOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Delegations ([]cid.Cid) (slice)
	if len("delegations") > 8192 {
		return fmt.Errorf("string in field \"delegations\" was too long")
	}
	if err := jw.WriteString(string("delegations")); err != nil {
		return fmt.Errorf("writing string for field \"delegations\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Delegations) > 8192 {
		return fmt.Errorf("slice value in field t.Delegations was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Delegations: %w", err)
	}
	for i, v := range t.Delegations {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Delegations: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("writing CID for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Delegations: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ClaimOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ClaimOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ClaimOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ClaimOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ClaimOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ClaimOK: string too large")
				}
				return fmt.Errorf("reading string for field ClaimOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ClaimOK: %w", err)
			}
			switch name {

			// t.Delegations ([]cid.Cid) (slice)
			case "delegations":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Delegations: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Delegations: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Delegations: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("reading CID for field item[0]: %w", err)
								}
								item[0] = c

							}
							t.Delegations = append(t.Delegations, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Delegations: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Delegations: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ClaimOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ClaimOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ClaimOK")
			}
		}
	}

	return nil
}
func (t *ConfirmArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Attenuations ([]access.CapabilityRequest) (slice)
	if len("att") > 8192 {
		return fmt.Errorf("string in field \"att\" was too long")
	}
	if err := jw.WriteString(string("att")); err != nil {
		return fmt.Errorf("writing string for field \"att\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Attenuations) > 8192 {
		return fmt.Errorf("slice value in field t.Attenuations was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Attenuations: %w", err)
	}
	for i, v := range t.Attenuations {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Attenuations: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Attenuations: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Audience (did.DID) (struct)
	if len("aud") > 8192 {
		return fmt.Errorf("string in field \"aud\" was too long")
	}
	if err := jw.WriteString(string("aud")); err != nil {
		return fmt.Errorf("writing string for field \"aud\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Audience.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Audience: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cause (cid.Cid) (struct)
	if len("cause") > 8192 {
		return fmt.Errorf("string in field \"cause\" was too long")
	}
	if err := jw.WriteString(string("cause")); err != nil {
		return fmt.Errorf("writing string for field \"cause\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Cause); err != nil {
		return fmt.Errorf("writing CID for field t.Cause: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Issuer (did.DID) (struct)
	if len("iss") > 8192 {
		return fmt.Errorf("string in field \"iss\" was too long")
	}
	if err := jw.WriteString(string("iss")); err != nil {
		return fmt.Errorf("writing string for field \"iss\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Issuer.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Issuer: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ConfirmArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ConfirmArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ConfirmArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ConfirmArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ConfirmArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ConfirmArguments: string too large")
				}
				return fmt.Errorf("reading string for field ConfirmArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ConfirmArguments: %w", err)
			}
			switch name {

			// t.Attenuations ([]access.CapabilityRequest) (slice)
			case "att":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Attenuations: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Attenuations: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Attenuations: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]CapabilityRequest, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Attenuations = append(t.Attenuations, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Attenuations: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Attenuations: slice too large")
							}
						}
					}

				}

				// t.Audience (did.DID) (struct)
			case "aud":

				if err := t.Audience.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Audience: %w", err)
				}

				// t.Cause (cid.Cid) (struct)
			case "cause":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Cause: %w", err)
					}
					t.Cause = c

				}

				// t.Issuer (did.DID) (struct)
			case "iss":

				if err := t.Issuer.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Issuer: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ConfirmArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ConfirmArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ConfirmArguments")
			}
		}
	}

	return nil
}
func (t *DelegateArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Delegations ([]cid.Cid) (slice)
	if len("delegations") > 8192 {
		return fmt.Errorf("string in field \"delegations\" was too long")
	}
	if err := jw.WriteString(string("delegations")); err != nil {
		return fmt.Errorf("writing string for field \"delegations\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Delegations) > 8192 {
		return fmt.Errorf("slice value in field t.Delegations was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Delegations: %w", err)
	}
	for i, v := range t.Delegations {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Delegations: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("writing CID for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Delegations: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *DelegateArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = DelegateArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for DelegateArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for DelegateArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for DelegateArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field DelegateArguments: string too large")
				}
				return fmt.Errorf("reading string for field DelegateArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field DelegateArguments: %w", err)
			}
			switch name {

			// t.Delegations ([]cid.Cid) (slice)
			case "delegations":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Delegations: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Delegations: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Delegations: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("reading CID for field item[0]: %w", err)
								}
								item[0] = c

							}
							t.Delegations = append(t.Delegations, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Delegations: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Delegations: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for DelegateArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field DelegateArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for DelegateArguments")
			}
		}
	}

	return nil
}
